import { createAgentSession } from "@earendil-works/pi-coding-agent";
import { join } from "node:path";
import { log } from "../util/log.js";
import { resolveProfile } from "../profiles/resolve.js";
import { registerCustomProviders } from "../profiles/custom-providers.js";
import { GitHubClient } from "../github/client.js";
import { Workspace, cloneUrlFor } from "./workspace.js";
import { buildPrompt } from "./prompt.js";
import {
  RunState,
  createCommentOnIssueTool,
  createFinishRunTool,
  type FinishRunResult,
} from "./tools.js";
import { installSkills } from "../util/paths.js";
import {
  AuthStorage,
  ModelRegistry,
  SessionManager,
  DefaultResourceLoader,
} from "@earendil-works/pi-coding-agent";
import type { NoodleConfig } from "../config/schema.js";

/** AuthStorage instance type (its constructor is private; use the factory's return type). */
type AuthStorageInstance = ReturnType<typeof AuthStorage.create>;

export interface RunInput {
  repo: string; // owner/name
  issueNumber: number;
  /** job id for tmp dir + logs + branch suffix */
  jobId?: string;
}

export interface RunResult {
  profile: string;
  model: string;
  changedFiles: string[];
  /** The agent's structured summary, if it called finish_run. */
  agentSummary?: FinishRunResult;
  prUrl?: string;
  commentUrl: string;
}

/**
 * Run one job end-to-end: fetch issue → route profile → clone → run pi →
 * commit → push → open PR → comment on issue.
 *
 * Assumes GITHUB_TOKEN is set (Phase 1 PAT auth).
 */
export async function runJob(
  config: NoodleConfig,
  gh: GitHubClient,
  input: RunInput,
  deps?: {
    /** Optional pre-built auth storage (carrying API keys). */
    authStorage?: AuthStorageInstance;
    /** Override for tests. Defaults to pi's createAgentSession. */
    createAgentSessionFn?: typeof createAgentSession;
  },
): Promise<RunResult> {
  const jobId = input.jobId ?? `${input.repo.replace("/", "-")}-${input.issueNumber}`;
  const log_ = log.child({ jobId, repo: input.repo, issue: input.issueNumber });

  // 1. Fetch issue + comments.
  const issue = await gh.getIssue(input.repo, input.issueNumber);
  const comments = await gh.getIssueComments(input.repo, input.issueNumber);
  log_.info({ title: issue.title, labels: issue.labels }, "fetched issue");

  // 2. Route to a profile.
  const profile = resolveProfile(config, {
    title: issue.title,
    body: issue.body,
    labels: issue.labels,
    comments: comments.map((c) => c.body),
  });
  log_.info({ profile: profile.name, model: profile.model }, "routed profile");

  // 3. Resolve the model via the registry.
  const authStorage = deps?.authStorage ?? AuthStorage.create();
  const modelRegistry = ModelRegistry.create(authStorage);
  // Register any custom-endpoint profiles (Ollama/vLLM/proxies) with pi first.
  registerCustomProviders(config, modelRegistry);
  let model;
  try {
    model = modelRegistry.find(profile.provider, profile.model);
  } catch (e) {
    throw new Error(
      `Could not resolve model "${profile.provider}/${profile.model}". ` +
        `Check the profile config and that the model id is valid. (${(e as Error).message})`,
    );
  }

  // 4. Clone + branch. Base = repo default branch (resolved dynamically).
  const baseBranch = await gh.defaultBranch(input.repo);
  const token = process.env.GITHUB_TOKEN!;
  const ws = await Workspace.clone(cloneUrlFor(input.repo, token), jobId);
  // Unique branch per run so re-runs don't collide on push.
  const branchName = makeBranchName(input.issueNumber, jobId);
  const state = new RunState();
  try {
    await ws.branch(branchName);
    await installSkills(ws.path);

    // 5. Build prompt + resource loader.
    const prompt = buildPrompt(issue, comments, input.repo);
    const loader = new DefaultResourceLoader({
      cwd: ws.path,
      agentDir: join(ws.path, ".noodle-agent"),
    });
    await loader.reload();

    // 6. Create pi session + run.
    const create = deps?.createAgentSessionFn ?? createAgentSession;
    const { session } = await create({
      cwd: ws.path,
      model,
      authStorage,
      modelRegistry,
      sessionManager: SessionManager.inMemory(),
      resourceLoader: loader,
      tools: profile.tools,
      customTools: [
        createCommentOnIssueTool(gh, input.repo, input.issueNumber),
        createFinishRunTool(state),
      ],
    });

    subscribeForLogging(session, log_);

    log_.info("starting agent run");
    await session.prompt(prompt);
    await session.dispose?.();
    log_.info(
      { calledFinishRun: !!state.result },
      "agent run finished",
    );

    // 7. Commit + (if changes) push + open PR.
    const committed = await ws.commitAll(
      `Fix #${input.issueNumber}: ${issue.title}\n\nGenerated by Noodle (profile: ${profile.name}).`,
    );

    let prUrl: string | undefined;
    if (committed) {
      await ws.push(branchName);
      const changedFiles = await ws.changedFiles();
      const prBody = buildPrBody(profile.name, changedFiles, issue.html_url, state.result);
      const pr = await gh.createPullRequest(
        input.repo,
        branchName,
        baseBranch,
        `Fixes #${issue.number}: ${issue.title}`,
        prBody,
      );
      prUrl = pr.html_url;
      log_.info({ pr: prUrl, changedFiles }, "opened PR");

      const commentBody = buildIssueComment(
        profile,
        pr.number,
        pr.html_url,
        changedFiles,
        state.result,
        /*committed=*/ true,
      );
      const commentUrl = await gh.createIssueComment(input.repo, input.issueNumber, commentBody);
      return {
        profile: profile.name,
        model: profile.model,
        changedFiles,
        agentSummary: state.result,
        prUrl,
        commentUrl,
      };
    }

    // 8. No changes — explain why.
    const commentBody = buildIssueComment(profile, undefined, undefined, [], state.result, false);
    const commentUrl = await gh.createIssueComment(input.repo, input.issueNumber, commentBody);
    log_.warn({ calledFinishRun: !!state.result }, "no changes produced");
    return {
      profile: profile.name,
      model: profile.model,
      changedFiles: [],
      agentSummary: state.result,
      commentUrl,
    };
  } finally {
    await ws.dispose();
  }
}

/** Branch name unique per run: noodle/issue-42-<shortid>. */
function makeBranchName(issueNumber: number, jobId: string): string {
  // short, readable suffix from the jobId (already unique per run)
  const suffix = jobId.replace(/^[\w./-]+-\d+-/, "").slice(0, 8) || Date.now().toString(36);
  return `noodle/issue-${issueNumber}-${suffix}`;
}

/** Attach a subscriber that mirrors pi events into Noodle's structured log. */
function subscribeForLogging(
  session: { subscribe?: (fn: (e: unknown) => void) => unknown },
  log_: typeof log,
) {
  if (typeof session.subscribe !== "function") return;
  session.subscribe((event: unknown) => {
    const e = event as { type?: string };
    switch (e.type) {
      case "tool_execution_start":
        log_.debug({ event: e.type }, "tool start");
        break;
      case "message_end":
        log_.debug({ event: e.type }, "message end");
        break;
      default:
        log_.trace({ event: e.type }, "pi event");
    }
  });
}

// --- output builders (exported for testing) --------------------------------
// The agent's structured summary provides the narrative; git provides the
// facts (changed files). When the agent didn't call finish_run (error, max
// tokens, weak model), we fall back to a deterministic template so the run
// still produces a usable PR body and comment.

export function buildPrBody(
  profile: string,
  changedFiles: string[],
  issueUrl: string,
  summary?: FinishRunResult,
): string {
  const lines: string[] = ["## Summary", ""];
  if (summary) {
    lines.push(summary.summary);
    if (summary.approach) lines.push("", `**Approach:** ${summary.approach}`);
  } else {
    lines.push(
      "_The agent did not return a structured summary. Please review the diff carefully._",
    );
  }
  lines.push("", "**Changed files:**", ...changedFiles.map((f) => `- \`${f}\``), "");
  if (summary?.needs_human_review) {
    lines.push("⚠️ **The agent flagged this change as needing human review.**", "");
  }
  lines.push(
    "---",
    `🤖 Generated by **Noodle** — \`${profile}\` profile.`,
    "",
    `Closes ${issueUrl}`,
  );
  return lines.join("\n");
}

export function buildIssueComment(
  profile: { name: string; provider: string; model: string },
  prNumber: number | undefined,
  prUrl: string | undefined,
  changedFiles: string[],
  summary: FinishRunResult | undefined,
  committed: boolean,
): string {
  const head = committed && prUrl
    ? `🤖 Noodle ran the **${profile.name}** profile (\`${profile.provider}/${profile.model}\`) and opened #${prNumber}: ${prUrl}`
    : `🤖 Noodle ran the **${profile.name}** profile (\`${profile.provider}/${profile.model}\`) but made no code changes.`;

  const lines = [head, ""];
  if (summary) {
    lines.push(`> ${summary.summary.replace(/\n/g, "\n> ")}`);
    if (summary.confidence) lines.push(``, `_Confidence: ${summary.confidence}_`);
  } else if (committed) {
    lines.push("_(The agent did not return a summary. See the PR diff for details.)_)");
  } else {
    lines.push(
      "This may mean the issue needs clarification, is not a code change, or the agent couldn't find the relevant code.",
    );
  }
  if (committed && changedFiles.length) {
    lines.push("", `Changed files: ${changedFiles.map((f) => `\`${f}\``).join(", ")}`);
  }
  return lines.join("\n");
}
